apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xuohrrsoe-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:853e0ee696d3942cd18a1f7ba8fa55c0d877a3bb@sha256:277e0e5eee993e268fca3115a4ab9b84ff2eef601be70e5443f0d3a92bf5f0fc
          name: container-image
